using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TestProject
{
    public partial class LookupTest : Form
    {
        private List<IsoCode> _IsoCodes { get; set; }
        public List<IsoCode> GetIsoCodes
        {
            get
            {
                if(_IsoCodes == null || _IsoCodes.Count ==0 )
                {
                    _IsoCodes = new List<IsoCode>()
                    {
new IsoCode("AD", "안도라", "ANDORRA"),
new IsoCode("AE", "아랍에미리트", "United Arab Emirates : UAE"),
new IsoCode("AF", "아프가니스탄", "AFGHANISTAN"),
new IsoCode("AG", "앤티가바부다", "Antigua and Barbuda"),
new IsoCode("AI", "앵귈라", "ANGUILLA"),
new IsoCode("AL", "알바니아", "ALBANIA"),
new IsoCode("AM", "아르메니아", "ARMENIA"),
new IsoCode("AN", "네덜란드령 안틸레스", "NETHERLANDS ANTILLES"),
new IsoCode("AO", "앙골라", "ANGOLA"),
new IsoCode("AQ", "영국령 남극지역", "British Antarctic Territy"),
new IsoCode("AR", "아르헨티나", "ARGENTINA"),
new IsoCode("AS", "아메리칸사모아", "AMERICAN SAMOA"),
new IsoCode("AT", "오스트리아", "AUSTRIA"),
new IsoCode("AU", "호주", "Australia"),
new IsoCode("AW", "아루바", "ARUBA"),
new IsoCode("AX", "올란드 제도", "AL ISLS"),
new IsoCode("AZ", "아제르바이잔", "AZERBAIJAN"),
new IsoCode("BA", "보스니아헤르체고비나", "Bosnia-Herzegovina"),
new IsoCode("BB", "바베이도스", "BARBADOS"),
new IsoCode("BD", "방글라데시", "BANGLADESH"),
new IsoCode("BE", "벨기에", "BELGIUM"),
new IsoCode("BF", "부르키나파소", "Burkina Faso"),
new IsoCode("BG", "불가리아", "BULGARIA"),
new IsoCode("BH", "바레인", "BAHRAIN"),
new IsoCode("BI", "부룬디", "BURUNDI"),
new IsoCode("BJ", "베냉", "BENIN"),
new IsoCode("BL", "세인트 바돌로메", "SAINT BARTHELEMY"),
new IsoCode("BM", "버뮤다", "BERMUDA"),
new IsoCode("BN", "브루나이", "Brunei"),
new IsoCode("BO", "볼리비아", "BOLIVIA"),
new IsoCode("BR", "브라질", "BRAZIL"),
new IsoCode("BS", "바하마", "BAHAMAS"),
new IsoCode("BT", "부탄", "BHUTAN"),
new IsoCode("BV", "부베 섬", "BOUVET ISL"),
new IsoCode("BW", "보츠와나", "BOTSWANA"),
new IsoCode("BY", "벨라루스", "BELARUS"),
new IsoCode("BZ", "벨리즈", "BELIZE"),
new IsoCode("CA", "캐나다", "CANADA"),
new IsoCode("CC", "코코스 제도", "COCOS ISLS"),
new IsoCode("CD", "콩고민주공화국(DR콩고)", "Democratic Republic of Congo"),
new IsoCode("CF", "중앙아프리카공화국", "CENTRAL AFRICAN REPUBLIC"),
new IsoCode("CG", "콩고공화국", "Congo"),
new IsoCode("CH", "스위스", "SWITZERLAND"),
new IsoCode("CI", "코트디부아르", "Cote DIvoire"),
new IsoCode("CK", "쿡제도", "Cook Islands"),
new IsoCode("CL", "칠레", "CHILE"),
new IsoCode("CM", "카메룬", "CAMEROON"),
new IsoCode("CN", "중국", "China"),
new IsoCode("CO", "콜롬비아", "COLOMBIA"),
new IsoCode("CR", "코스타리카", "COSTA RICA"),
new IsoCode("CU", "쿠바", "CUBA"),
new IsoCode("CV", "카보베르데", "CAPE VERDE"),
new IsoCode("CX", "크리스마스 섬", "CHRISTMAS ISL"),
new IsoCode("CY", "사이프러스", "Cyprus"),
new IsoCode("CZ", "체코", "Czech"),
new IsoCode("DE", "독일", "GERMANY"),
new IsoCode("DJ", "지부티", "DJIBOUTI"),
new IsoCode("DK", "덴마크", "DENMARK"),
new IsoCode("DM", "도미니카연방", "DOMINICA"),
new IsoCode("DO", "도미니카공화국", "Dominican Republic"),
new IsoCode("DZ", "알제리", "ALGERIA"),
new IsoCode("EC", "에콰도르", "ECUADOR"),
new IsoCode("EE", "에스토니아", "ESTONIA"),
new IsoCode("EG", "이집트", "EGYPT"),
new IsoCode("EH", "사하라 아랍민주공화국(서부사하라)", "Sahara Arab Democratic Republic"),
new IsoCode("ER", "에리트리아", "ERITREA"),
new IsoCode("ES", "스페인", "SPAIN"),
new IsoCode("ET", "에티오피아", "ETHIOPIA"),
new IsoCode("FI", "핀란드", "FINLAND"),
new IsoCode("FJ", "피지", "FIJI"),
new IsoCode("FK", "포클랜드(말비나스)군도", "FALKL ISLS (MALVINAS)"),
new IsoCode("FM", "마이크로네시아연방", "Federated States of Micronesia"),
new IsoCode("FO", "페로 제도", "FAROE ISLS"),
new IsoCode("FR", "프랑스", "FRANCE"),
new IsoCode("FX", "프랑스 본국", "FRANCE, METROPOLITAN"),
new IsoCode("GA", "가봉", "GABON"),
new IsoCode("GB", "영국", "UNITED KINGDOM"),
new IsoCode("GD", "그레나다", "GRENADA"),
new IsoCode("GE", "조지아", "Gegia"),
new IsoCode("GF", "프랑스령 기아나", "FRENCH GUIANA"),
new IsoCode("GG", "건지", "Bailiwick of Guernsey"),
new IsoCode("GH", "가나", "GHANA"),
new IsoCode("GI", "지브롤터", "GIBRALTAR"),
new IsoCode("GL", "그린란드", "Greenland"),
new IsoCode("GM", "감비아", "GAMBIA"),
new IsoCode("GN", "기니", "GUINEA"),
new IsoCode("GP", "과들루프", "GUADELOUPE"),
new IsoCode("GQ", "적도기니", "Equatial Guinea"),
new IsoCode("GR", "그리스", "GREECE"),
new IsoCode("GS", "사우스조지아 사우스샌드위치 제도", "SOUTH GEGIA  THE SOUTH SWICH ISLS"),
new IsoCode("GT", "과테말라", "GUATEMALA"),
new IsoCode("GU", "괌", "GUAM"),
new IsoCode("GW", "기니비사우", "GUINEA-BISSAU"),
new IsoCode("GY", "가이아나", "GUYANA"),
new IsoCode("HK", "홍콩", "Hongkong"),
new IsoCode("HM", "허드 맥도널드 제도", "HEARD  MC DONALD ISLS"),
new IsoCode("HN", "온두라스", "HONDURAS"),
new IsoCode("HR", "크로아티아", "CROATIA"),
new IsoCode("HT", "아이티", "HAITI"),
new IsoCode("HU", "헝가리", "HUNGARY"),
new IsoCode("ID", "인도네시아", "INDONESIA"),
new IsoCode("IE", "아일랜드", "IRELAND"),
new IsoCode("IL", "이스라엘", "ISRAEL"),
new IsoCode("IM", "맨 섬", "Isle of Man"),
new IsoCode("IN", "인도", "INDIA"),
new IsoCode("IO", "영국령 인도양 제도", "British Indian Ocean Territy"),
new IsoCode("IQ", "이라크", "IRAQ"),
new IsoCode("IR", "이란", "IRAN"),
new IsoCode("IS", "아이슬란드", "ICELAND"),
new IsoCode("IT", "이탈리아", "ITALY"),
new IsoCode("JE", "저지", "Bailiwick of Jersey"),
new IsoCode("JM", "자메이카", "JAMAICA"),
new IsoCode("JO", "요르단", "JORDAN"),
new IsoCode("JP", "일본", "JAPAN"),
new IsoCode("KE", "케냐", "KENYA"),
new IsoCode("KG", "키르기즈", "Kyrgyz"),
new IsoCode("KH", "캄보디아", "CAMBODIA"),
new IsoCode("KI", "키리바시", "KIRIBATI"),
new IsoCode("KM", "코모로", "COMOROS"),
new IsoCode("KN", "세인트 킷츠 네비스", "SAINT KITTS  NEVIS"),
new IsoCode("KP", "조선민주주의인민공화국", "KEA, DEMOCRATIC PEOPLES REPUBLIC OF"),
new IsoCode("KR", "대한민국", "Korea"),
new IsoCode("KW", "쿠웨이트", "KUWAIT"),
new IsoCode("KY", "케이맨제도", "Cayman Islands"),
new IsoCode("KZ", "카자흐스탄", "KAZAKHSTAN"),
new IsoCode("LA", "라오스", "Laos"),
new IsoCode("LB", "레바논", "LEBANON"),
new IsoCode("LC", "세인트 루시아", "St. Lucia"),
new IsoCode("LI", "리히텐슈타인", "LIECHTENSTEIN"),
new IsoCode("LK", "스리랑카", "SRI LANKA"),
new IsoCode("LR", "라이베리아", "LIBERIA"),
new IsoCode("LS", "레소토", "LESOTHO"),
new IsoCode("LT", "리투아니아", "LITHUANIA"),
new IsoCode("LU", "룩셈부르크", "LUXEMBOURG"),
new IsoCode("LV", "라트비아", "LATVIA"),
new IsoCode("LY", "리비아", "Libya"),
new IsoCode("MA", "모로코", "MOROCCO"),
new IsoCode("MC", "모나코", "MONACO"),
new IsoCode("MD", "몰도바", "Moldova"),
new IsoCode("ME", "몬테네그로", "MONTENEGRO"),
new IsoCode("MF", "세인트 마틴", "SAINT MARTIN"),
new IsoCode("MG", "마다가스카르", "MADAGASCAR"),
new IsoCode("MH", "마셜제도", "Marshall Islands"),
new IsoCode("MK", "북마케도니아", "Nth Macedonia"),
new IsoCode("ML", "말리", "MALI"),
new IsoCode("MM", "미얀마", "MYANMAR"),
new IsoCode("MN", "몽골", "MONGOLIA"),
new IsoCode("MO", "마카오", "MACAO"),
new IsoCode("MP", "북마리아나군도", "NTHERN MARIANA ISLS"),
new IsoCode("MQ", "마르티니크", "MARTINIQUE"),
new IsoCode("MR", "모리타니아", "Mauritania"),
new IsoCode("MS", "몬트세랫", "MONTSERRAT"),
new IsoCode("MT", "몰타", "MALTA"),
new IsoCode("MU", "모리셔스", "MAURITIUS"),
new IsoCode("MV", "몰디브", "MALDIVES"),
new IsoCode("MW", "말라위", "MALAWI"),
new IsoCode("MX", "멕시코", "MEXICO"),
new IsoCode("MY", "말레이시아", "MALAYSIA"),
new IsoCode("MZ", "모잠비크", "MOZAMBIQUE"),
new IsoCode("NA", "나미비아", "NAMIBIA"),
new IsoCode("NC", "뉴 칼레도니아", "New Caledonia"),
new IsoCode("NE", "니제르", "NIGER"),
new IsoCode("NF", "노퍽섬", "NFOLK ISL"),
new IsoCode("NG", "나이지리아", "NIGERIA"),
new IsoCode("NI", "니카라과", "NICARAGUA"),
new IsoCode("NL", "네덜란드", "NETHERLANDS"),
new IsoCode("NO", "노르웨이", "NORWAY"),
new IsoCode("NP", "네팔", "NEPAL"),
new IsoCode("NR", "나우루", "NAURU"),
new IsoCode("NU", "니우에", "NIUE"),
new IsoCode("NZ", "뉴질랜드", "NEW ZEALAND"),
new IsoCode("OM", "오만", "OMAN"),
new IsoCode("PA", "파나마", "PANAMA"),
new IsoCode("PE", "페루", "PERU"),
new IsoCode("PF", "프랑스령 폴리네시아", "FRENCH POLYNESIA"),
new IsoCode("PG", "파푸아뉴기니", "Papua New Guinea :PNG"),
new IsoCode("PH", "필리핀", "PHILIPPINES"),
new IsoCode("PK", "파키스탄", "PAKISTAN"),
new IsoCode("PL", "폴란드", "POLAND"),
new IsoCode("PM", "생피에르·미클롱", "St. Pierre  Miquelon"),
new IsoCode("PN", "핏케언 섬", "Pitcairn Islands"),
new IsoCode("PR", "푸에르토리코", "PUERTO RICO"),
new IsoCode("PS", "팔레스타인", "PALESTINE"),
new IsoCode("PT", "포르투갈", "PORTUGAL"),
new IsoCode("PW", "팔라우", "PALAU"),
new IsoCode("PY", "파라과이", "PARAGUAY"),
new IsoCode("QA", "카타르", "QATAR"),
new IsoCode("RE", "레위니옹", "REUNION"),
new IsoCode("RO", "루마니아", "ROMANIA"),
new IsoCode("RS", "세르비아", "SERBIA"),
new IsoCode("RU", "러시아", "Russia"),
new IsoCode("RW", "르완다", "RWANDA"),
new IsoCode("SA", "사우디아라비아", "SAUDI ARABIA"),
new IsoCode("SB", "솔로몬제도", "Solomon Islands"),
new IsoCode("SC", "세이셸", "SEYCHELLES"),
new IsoCode("SD", "수단", "SUDAN"),
new IsoCode("SE", "스웨덴", "SWEDEN"),
new IsoCode("SG", "싱가포르", "SINGAPORE"),
new IsoCode("SH", "세인트 헬레나 섬", "St Helena"),
new IsoCode("SI", "슬로베니아", "SLOVENIA"),
new IsoCode("SJ", "스발바르 얀마옌", "SVALBARD  JAN MAYEN ISLS"),
new IsoCode("SK", "슬로바키아", "SLOVAKIA"),
new IsoCode("SL", "시에라리온", "SIERRA LEONE"),
new IsoCode("SM", "산마리노", "SAN MARINO"),
new IsoCode("SN", "세네갈", "SENEGAL"),
new IsoCode("SO", "소말리아", "SOMALIA"),
new IsoCode("SR", "수리남", "SURINAME"),
new IsoCode("SS", "남수단", "South Sudan"),
new IsoCode("ST", "상투메프린시페", "Sao Tome Principe"),
new IsoCode("SV", "엘살바도르", "EL SALVADOR"),
new IsoCode("SY", "시리아", "Syria"),
new IsoCode("SZ", "에스와티니", "Eswatini"),
new IsoCode("TC", "터크스·케이커스 제도", "Turks and Caicos Islands"),
new IsoCode("TD", "차드", "CHAD"),
new IsoCode("TF", "프랑스령 남부와 남극 지역", "FRENCH SOUTHERN TERRITIES"),
new IsoCode("TG", "토고", "TOGO"),
new IsoCode("TH", "태국", "Thailand"),
new IsoCode("TJ", "타지키스탄", "TAJIKISTAN"),
new IsoCode("TK", "토켈라우", "TOKELAU"),
new IsoCode("TL", "동티모르", "Tim-Leste"),
new IsoCode("TM", "투르크메니스탄", "TURKMENISTAN"),
new IsoCode("TN", "튀니지", "TUNISIA"),
new IsoCode("TO", "통가", "TONGA"),
new IsoCode("TR", "튀르키예공화국", "TURKEY"),
new IsoCode("TT", "트리니다드토바고", "Trinidad Tobago"),
new IsoCode("TV", "투발루", "TUVALU"),
new IsoCode("TW", "타이완", "Taiwan"),
new IsoCode("TZ", "탄자니아", "Tanzania"),
new IsoCode("UA", "우크라이나", "UKRAINE"),
new IsoCode("UG", "우간다", "UGANDA"),
new IsoCode("UM", "미국령 군소 제도", "UNITED STATES MIN OUTLYING ISLS"),
new IsoCode("US", "미국", "United States of America"),
new IsoCode("UY", "우루과이", "URUGUAY"),
new IsoCode("UZ", "우즈베키스탄", "UZBEKISTAN"),
new IsoCode("VA", "교황청", "Vatican"),
new IsoCode("VC", "세인트 빈센트 그레나딘", "St. Vincent &#38;amp; the Grenadines"),
new IsoCode("VE", "베네수엘라", "VENEZUELA"),
new IsoCode("VG", "영국령 버진 아일랜드", "British Virgin Islands"),
new IsoCode("VI", "미국령 버진아일랜드", "VIRGIN ISLS, U.S."),
new IsoCode("VN", "베트남", "VIET NAM"),
new IsoCode("VU", "바누아투", "VANUATU"),
new IsoCode("WF", "왈리스·퓌튀나", "Wallis and Futuna"),
new IsoCode("WS", "사모아", "SAMOA"),
new IsoCode("XK", "코소보", "Kosovo"),
new IsoCode("YE", "예멘", "Yemen"),
new IsoCode("YT", "마요트", "MAYOTTE"),
new IsoCode("YU", "유고슬라비아", "YUGOSLAVIA"),
new IsoCode("ZA", "남아프리카공화국", "SOUTH AFRICA"),
new IsoCode("ZM", "잠비아", "ZAMBIA"),
new IsoCode("ZW", "짐바브웨", "ZIMBABWE")
                    };
                }

                return _IsoCodes;
            }
        }

        private List<JobCode> _jobCodes { get; set; }
        public List<JobCode> GetJobCodes
        {
            get
            {
                if (_jobCodes == null || _jobCodes.Count == 0)
                {
                    _jobCodes = new List<JobCode>() {
new JobCode("1110", "의회 의원∙고위 공무원 및 공공단체 임원"),
new JobCode("1120", "기업 고위 임원"),
new JobCode("1211", "정부행정 관리자"),
new JobCode("1212", "경영 지원 관리자"),
new JobCode("1220", "마케팅 및 광고∙홍보 관리자"),
new JobCode("1311", "연구 관리자"),
new JobCode("1312", "교육 관리자"),
new JobCode("1313", "법률∙경찰∙소방 및 교도 관리자"),
new JobCode("1320", "보험 및 금융 관리자"),
new JobCode("1331", "보건 의료 관련 관리자"),
new JobCode("1332", "사회복지 관련 관리자"),
new JobCode("1340", "문화∙예술 관련 관리자"),
new JobCode("1350", "정보 통신 관련 관리자"),
new JobCode("1390", "기타 전문 서비스 관리자"),
new JobCode("1411", "건설 및 광업 관련 관리자"),
new JobCode("1412", "전기∙가스 및 수도 관련 관리자"),
new JobCode("1413", "제품 생산 관련 관리자"),
new JobCode("1490", "기타 건설∙전기 및 생산 관련 관리자"),
new JobCode("1511", "영업 및 판매 관련 관리자"),
new JobCode("1512", "운송 관련 관리자"),
new JobCode("1521", "숙박∙여행∙오락 및 스포츠 관련 관리자"),
new JobCode("1522", "음식 서비스 관련 관리자"),
new JobCode("1530", "환경∙청소 및 경비 관련 관리자"),
new JobCode("1590", "기타 판매 및 고객 서비스 관리자"),
new JobCode("2111", "생명과학 연구원"),
new JobCode("2112", "자연과학 연구원"),
new JobCode("2121", "인문과학 연구원"),
new JobCode("2122", "사회과학 연구원"),
new JobCode("2131", "생명과학 시험원"),
new JobCode("2132", "농림∙어업 관련 시험원"),
new JobCode("2133", "자연과학 시험원"),
new JobCode("2211", "컴퓨터 하드웨어 기술자 및 연구원"),
new JobCode("2212", "통신공학 기술자 및 연구원"),
new JobCode("2221", "컴퓨터 시스템 전문가"),
new JobCode("2222", "시스템 소프트웨어 개발자"),
new JobCode("2223", "응용 소프트웨어 개발자"),
new JobCode("2224", "웹 개발자"),
new JobCode("2229", "기타 컴퓨터 시스템 및 소프트웨어 전문가"),
new JobCode("2231", "데이터 전문가"),
new JobCode("2232", "네트워크 시스템 개발자"),
new JobCode("2233", "정보 보안 전문가"),
new JobCode("2239", "기타 데이터 및 네트워크 관련 전문가"),
new JobCode("2241", "정보 시스템 운영자"),
new JobCode("2242", "웹 운영자"),
new JobCode("2250", "통신 및 방송 송출 장비 기사"),
new JobCode("2311", "건축가"),
new JobCode("2312", "건축공학 기술자"),
new JobCode("2313", "토목공학 기술자"),
new JobCode("2314", "조경 기술자"),
new JobCode("2315", "도시 및 교통 관련 전문가"),
new JobCode("2316", "측량 및 지리 정보 전문가"),
new JobCode("2317", "건설자재 시험원"),
new JobCode("2321", "화학공학 기술자 및 연구원"),
new JobCode("2322", "화학공학 시험원"),
new JobCode("2331", "금속∙재료 공학 연구원 및 기술자"),
new JobCode("2332", "금속 및 재료 공학 시험원"),
new JobCode("2341", "전기공학 기술자 및 연구원"),
new JobCode("2342", "전자공학 기술자 및 연구원"),
new JobCode("2343", "전기 및 전자공학 시험원"),
new JobCode("2351", "기계공학 기술자 및 연구원"),
new JobCode("2352", "로봇공학 기술자 및 연구원"),
new JobCode("2353", "기계 및 로봇공학 시험원"),
new JobCode("2361", "방재 기술자 및 연구원"),
new JobCode("2362", "소방공학 기술자 및 연구원"),
new JobCode("2363", "소방공학 시험원"),
new JobCode("2364", "산업 안전 및 위험 관리원"),
new JobCode("2365", "보건 위생 및 환경 검사원"),
new JobCode("2366", "비파괴 검사원"),
new JobCode("2371", "환경공학 기술자 및 연구원"),
new JobCode("2372", "가스∙에너지 기술자 및 연구원"),
new JobCode("2373", "환경공학 시험원"),
new JobCode("2374", "가스 및 에너지 시험원"),
new JobCode("2381", "항공기 조종사"),
new JobCode("2382", "선장∙항해사 및 도선사"),
new JobCode("2383", "관제사"),
new JobCode("2391", "식품공학 기술자 및 연구원"),
new JobCode("2392", "섬유공학 기술자 및 연구원"),
new JobCode("2393", "식품공학 시험원"),
new JobCode("2394", "섬유공학 시험원"),
new JobCode("2395", "제도사"),
new JobCode("2399", "기타 공학 관련 기술자 및 시험원"),
new JobCode("2411", "전문 의사"),
new JobCode("2412", "일반 의사"),
new JobCode("2413", "한의사"),
new JobCode("2414", "치과 의사"),
new JobCode("2415", "수의사"),
new JobCode("2420", "약사 및 한약사"),
new JobCode("2430", "간호사"),
new JobCode("2440", "영양사"),
new JobCode("2451", "임상병리사"),
new JobCode("2452", "방사선사"),
new JobCode("2453", "치과기공사"),
new JobCode("2454", "치과위생사"),
new JobCode("2455", "재활공학 기사"),
new JobCode("2456", "물리 및 작업 치료사"),
new JobCode("2457", "임상심리사"),
new JobCode("2459", "기타 치료∙재활사 및 의료기사"),
new JobCode("2461", "응급 구조사"),
new JobCode("2462", "위생사"),
new JobCode("2463", "안경사"),
new JobCode("2464", "의무 기록사"),
new JobCode("2465", "간호조무사"),
new JobCode("2466", "안마사"),
new JobCode("2471", "사회복지사"),
new JobCode("2472", "보육교사"),
new JobCode("2473", "직업상담사"),
new JobCode("2474", "상담 전문가"),
new JobCode("2475", "청소년 지도사"),
new JobCode("2476", "시민 단체 활동가"),
new JobCode("2479", "기타 사회복지 관련 종사원"),
new JobCode("2481", "성직자"),
new JobCode("2489", "기타 종교 관련 종사원"),
new JobCode("2511", "대학교수"),
new JobCode("2512", "대학 시간강사"),
new JobCode("2521", "중∙고등학교 교사"),
new JobCode("2522", "초등학교 교사"),
new JobCode("2523", "특수교육 교사"),
new JobCode("2530", "유치원 교사"),
new JobCode("2541", "문리 및 어학 강사"),
new JobCode("2542", "컴퓨터 강사"),
new JobCode("2543", "기술 및 기능계 강사"),
new JobCode("2544", "예능 강사"),
new JobCode("2545", "학습지 및 교육 교구 방문강사"),
new JobCode("2549", "기타 문리∙기술 및 예능 강사"),
new JobCode("2591", "장학관∙연구관 및 교육 관련 전문가"),
new JobCode("2592", "대학 교육 조교"),
new JobCode("2599", "기타 교사"),
new JobCode("2611", "판사 및 검사"),
new JobCode("2612", "변호사"),
new JobCode("2613", "법무사 및 집행관"),
new JobCode("2614", "변리사"),
new JobCode("2619", "기타 법률 전문가"),
new JobCode("2620", "정부 및 공공 행정 전문가"),
new JobCode("2711", "인사 및 노사 관련 전문가"),
new JobCode("2712", "회계사"),
new JobCode("2713", "세무사"),
new JobCode("2714", "관세사"),
new JobCode("2715", "경영 및 진단 전문가"),
new JobCode("2721", "투자 및 신용 분석가"),
new JobCode("2722", "자산 운용가"),
new JobCode("2723", "보험 및 금융 상품 개발자"),
new JobCode("2724", "증권 및 외환 딜러"),
new JobCode("2725", "손해 사정사"),
new JobCode("2729", "기타 금융 및 보험 관련 전문가"),
new JobCode("2731", "상품 기획 전문가"),
new JobCode("2732", "여행 상품 개발자"),
new JobCode("2733", "광고 및 홍보 전문가"),
new JobCode("2734", "조사 전문가"),
new JobCode("2735", "행사 기획자"),
new JobCode("2741", "감정 관련 전문가"),
new JobCode("2742", "해외 영업원"),
new JobCode("2743", "기술 영업원"),
new JobCode("2744", "상품 중개인 및 경매사"),
new JobCode("2745", "부동산 컨설턴트 및 중개사"),
new JobCode("2749", "기타 기술 영업 및 중개 관련 종사원"),
new JobCode("2811", "작가"),
new JobCode("2812", "출판물 전문가"),
new JobCode("2813", "기자 및 언론 관련 전문가"),
new JobCode("2814", "번역가 및 통역가"),
new JobCode("2821", "학예사 및 문화재 보존원"),
new JobCode("2822", "사서 및 기록물 관리사"),
new JobCode("2831", "감독 및 기술 감독"),
new JobCode("2832", "배우 및 모델"),
new JobCode("2833", "아나운서 및 리포터"),
new JobCode("2834", "촬영기사"),
new JobCode("2835", "음향 및 녹음 기사"),
new JobCode("2836", "영상∙녹화 및 편집 기사"),
new JobCode("2837", "조명기사 및 영사기사"),
new JobCode("2839", "기타 연극∙영화 및 영상 관련 종사원"),
new JobCode("2841", "화가 및 조각가"),
new JobCode("2842", "사진기자 및 사진가"),
new JobCode("2843", "만화가 및 만화영화 작가"),
new JobCode("2844", "국악 및 전통 예능인"),
new JobCode("2845", "지휘자∙작곡가 및 연주가"),
new JobCode("2846", "가수 및 성악가"),
new JobCode("2847", "무용가 및 안무가"),
new JobCode("2849", "기타 시각 및 공연 예술가"),
new JobCode("2851", "제품 디자이너"),
new JobCode("2852", "패션 디자이너"),
new JobCode("2853", "실내장식 디자이너"),
new JobCode("2854", "시각 디자이너"),
new JobCode("2855", "미디어 콘텐츠 디자이너"),
new JobCode("2861", "스포츠 감독 및 코치"),
new JobCode("2862", "직업 운동선수"),
new JobCode("2863", "경기 심판 및 경기 기록원"),
new JobCode("2869", "기타 스포츠 및 레크리에이션 관련 전문가"),
new JobCode("2870", "주방장 및 요리 연구가"),
new JobCode("2881", "공연·영화 및 음반 기획자"),
new JobCode("2882", "연예인 및 스포츠 매니저"),
new JobCode("3111", "조세행정 사무원"),
new JobCode("3112", "관세행정 사무원"),
new JobCode("3113", "병무행정 사무원"),
new JobCode("3114", "국가 및 지방 행정 사무원"),
new JobCode("3115", "공공행정 사무원"),
new JobCode("3121", "기획 및 마케팅 사무원"),
new JobCode("3122", "인사 및 교육∙훈련 사무원"),
new JobCode("3123", "자재 관리 사무원"),
new JobCode("3124", "생산 및 품질 관리 사무원"),
new JobCode("3125", "무역 사무원"),
new JobCode("3126", "운송 사무원"),
new JobCode("3127", "총무 사무원 및 대학 행정조교"),
new JobCode("3131", "회계 사무원"),
new JobCode("3132", "경리 사무원"),
new JobCode("3141", "비서"),
new JobCode("3142", "전산 자료 입력원 및 사무 보조원"),
new JobCode("3201", "출납 창구 사무원"),
new JobCode("3202", "보험 심사원 및 사무원"),
new JobCode("3203", "은행 사무원"),
new JobCode("3204", "증권 사무원"),
new JobCode("3205", "수금원 및 신용 추심원"),
new JobCode("3209", "기타 금융 사무원"),
new JobCode("3301", "법률 관련 사무원"),
new JobCode("3302", "감사 사무원"),
new JobCode("3910", "통계 관련 사무원"),
new JobCode("3921", "여행 사무원"),
new JobCode("3922", "안내∙접수원 및 전화교환원"),
new JobCode("3991", "고객 상담 및 모니터 요원"),
new JobCode("3999", "기타 사무원"),
new JobCode("4111", "경찰관 및 수사관"),
new JobCode("4112", "소방관"),
new JobCode("4113", "소년원 학교 교사 및 교도관"),
new JobCode("4121", "경호원"),
new JobCode("4122", "청원경찰"),
new JobCode("4123", "시설 및 특수 경비원"),
new JobCode("4129", "기타 경호 및 보안 관련 종사원"),
new JobCode("4211", "돌봄 서비스 종사원"),
new JobCode("4212", "보육 및 교사 보조 서비스 종사원"),
new JobCode("4219", "기타 돌봄 및 보건 서비스 종사원"),
new JobCode("4221", "이용사"),
new JobCode("4222", "미용사"),
new JobCode("4223", "피부 및 체형 관리사"),
new JobCode("4224", "메이크업 아티스트 및 분장사"),
new JobCode("4229", "기타 미용 관련 서비스 종사원"),
new JobCode("4231", "결혼상담원 및 웨딩플래너"),
new JobCode("4232", "혼례 종사원"),
new JobCode("4233", "장례 상담원 및 장례 지도사"),
new JobCode("4291", "반려동물 미용 및 관리 종사원"),
new JobCode("4292", "점술가 및 민속신앙 종사원"),
new JobCode("4293", "개인 생활 서비스 종사원"),
new JobCode("4311", "항공기 객실 승무원"),
new JobCode("4312", "선박 및 열차 객실 승무원"),
new JobCode("4321", "여가 및 관광 서비스 종사원"),
new JobCode("4322", "숙박시설 서비스 종사원"),
new JobCode("4323", "오락시설 서비스 종사원"),
new JobCode("4329", "기타 여가 서비스 종사원"),
new JobCode("4411", "한식 조리사"),
new JobCode("4412", "중식 조리사"),
new JobCode("4413", "양식 조리사"),
new JobCode("4414", "일식 조리사"),
new JobCode("4415", "음료 조리사"),
new JobCode("4419", "기타 조리사"),
new JobCode("4421", "바텐더"),
new JobCode("4422", "웨이터"),
new JobCode("4429", "기타 음식 서비스 종사원"),
new JobCode("5101", "자동차 영업원"),
new JobCode("5102", "제품 및 광고 영업원"),
new JobCode("5103", "보험 모집인 및 투자 권유 대행인"),
new JobCode("5104", "대출 및 신용카드 모집인"),
new JobCode("5211", "소규모 상점 경영 및 일선 관리 종사원"),
new JobCode("5212", "상점 판매원"),
new JobCode("5213", "매표원 및 복권 판매원"),
new JobCode("5214", "매장 계산원 및 요금 정산원"),
new JobCode("5220", "상품 대여원"),
new JobCode("5311", "단말기 및 통신 서비스 판매원"),
new JobCode("5312", "온라인 쇼핑 판매원"),
new JobCode("5313", "텔레마케터"),
new JobCode("5321", "방문 판매원"),
new JobCode("5322", "노점 및 이동 판매원"),
new JobCode("5323", "홍보 도우미 및 판촉원"),
new JobCode("6111", "곡식작물 재배원"),
new JobCode("6112", "채소 및 특용작물 재배원"),
new JobCode("6113", "과수작물 재배원"),
new JobCode("6121", "원예작물 재배원"),
new JobCode("6122", "조경원"),
new JobCode("6131", "낙농업 관련 종사원"),
new JobCode("6132", "가축 사육 종사원"),
new JobCode("6139", "기타 사육 관련 종사원"),
new JobCode("6201", "조림∙산림경영인 및 벌목원"),
new JobCode("6209", "임산물 채취 및 기타 임업 관련 종사원"),
new JobCode("6301", "양식원"),
new JobCode("6302", "어부 및 해녀"),
new JobCode("7101", "제빵사 및 제과원"),
new JobCode("7102", "떡 제조원"),
new JobCode("7103", "정육가공원 및 도축원"),
new JobCode("7104", "식품 및 담배 등급원"),
new JobCode("7105", "김치 및 밑반찬 제조 종사원"),
new JobCode("7109", "기타 식품가공 관련 종사원"),
new JobCode("7211", "패턴사"),
new JobCode("7212", "재단사"),
new JobCode("7213", "재봉사"),
new JobCode("7214", "제화원"),
new JobCode("7219", "기타 섬유 및 가죽 관련 기능 종사원"),
new JobCode("7221", "한복 제조원"),
new JobCode("7222", "양장 및 양복 제조원"),
new JobCode("7223", "모피 및 가죽 의복 제조원"),
new JobCode("7224", "의복∙가죽 및 모피 수선원"),
new JobCode("7229", "기타 의복 제조 관련 기능 종사원"),
new JobCode("7301", "목제품 제조 관련 종사원"),
new JobCode("7302", "가구 제조 및 수리원"),
new JobCode("7303", "악기 제조 및 조율사"),
new JobCode("7304", "간판 제작 및 설치원"),
new JobCode("7411", "금형원"),
new JobCode("7412", "주조원"),
new JobCode("7413", "단조원"),
new JobCode("7421", "제관원"),
new JobCode("7422", "판금원"),
new JobCode("7430", "용접원"),
new JobCode("7510", "자동차 정비원"),
new JobCode("7521", "항공기 정비원"),
new JobCode("7522", "선박 정비원"),
new JobCode("7523", "철도 기관차 및 전동차 정비원"),
new JobCode("7529", "기타 운송장비 정비원"),
new JobCode("7531", "공업기계 설치 및 정비원"),
new JobCode("7532", "승강기 설치 및 정비원"),
new JobCode("7533", "물품 이동 장비 설치 및 정비원"),
new JobCode("7534", "냉동∙냉장∙공조기 설치 및 정비원"),
new JobCode("7535", "보일러 설치 및 정비원"),
new JobCode("7536", "건설∙광업기계 설치 및 정비원"),
new JobCode("7539", "농업용∙기타 기계장비 설치 및 정비원"),
new JobCode("7611", "사무용 전자기기 설치 및 수리원"),
new JobCode("7612", "가전제품 설치 및 수리원"),
new JobCode("7619", "기타 전기∙전자기기 설치 및 수리원"),
new JobCode("7621", "산업 전기공"),
new JobCode("7622", "내선 전기공"),
new JobCode("7623", "외선 전기공"),
new JobCode("7711", "컴퓨터 설치 및 수리원"),
new JobCode("7712", "이동전화기 수리원"),
new JobCode("7719", "기타 정보 통신기기 설치 및 수리원"),
new JobCode("7721", "방송 관련 장비 설치 및 수리원"),
new JobCode("7722", "통신 관련 장비 설치 및 수리원"),
new JobCode("7723", "통신·방송∙인터넷케이블 설치 및 수리원"),
new JobCode("7811", "강구조물 가공원 및 건립원"),
new JobCode("7812", "경량 철골공"),
new JobCode("7821", "철근공"),
new JobCode("7822", "콘크리트공"),
new JobCode("7823", "건축 석공"),
new JobCode("7824", "건축 목공"),
new JobCode("7825", "조적공 및 석재 부설원"),
new JobCode("7829", "기타 건설 관련 기능 종사원"),
new JobCode("7831", "미장공"),
new JobCode("7832", "방수공"),
new JobCode("7833", "단열공"),
new JobCode("7834", "바닥재 시공원"),
new JobCode("7835", "도배공 및 유리 부착원"),
new JobCode("7836", "건축 도장공"),
new JobCode("7837", "새시 조립 및 설치원"),
new JobCode("7839", "기타 건축 마감 관련 기능 종사원"),
new JobCode("7841", "광원∙채석원 및 석재 절단원"),
new JobCode("7842", "철로 설치 및 보수원"),
new JobCode("7849", "기타 채굴 및 토목 관련 종사원"),
new JobCode("7911", "공예원"),
new JobCode("7912", "귀금속 및 보석 세공원"),
new JobCode("7921", "건설 배관공"),
new JobCode("7922", "공업 배관공"),
new JobCode("7929", "기타 배관공"),
new JobCode("7991", "배관 세정원 및 방역원"),
new JobCode("7999", "기타 기능 관련 종사원"),
new JobCode("8111", "제분 및 도정 관련 기계 조작원"),
new JobCode("8112", "곡물가공 제품 기계 조작원"),
new JobCode("8113", "육류∙어패류 및 낙농품 가공 기계 조작원"),
new JobCode("8114", "과실 및 채소 가공 관련 기계 조작원"),
new JobCode("8120", "음료 제조 관련 기계 조작원"),
new JobCode("8190", "기타 식품가공 관련 기계 조작원"),
new JobCode("8211", "섬유 제조 기계 조작원"),
new JobCode("8212", "표백 및 염색 관련 기계 조작원"),
new JobCode("8221", "직조기 및 편직기 조작원"),
new JobCode("8222", "신발 제조기 조작원 및 조립원"),
new JobCode("8229", "기타 직물∙신발 관련 기계 조작원 및 조립원"),
new JobCode("8230", "세탁 관련 기계 조작원"),
new JobCode("8311", "석유 및 천연가스 제조 관련 제어 장치 조작원"),
new JobCode("8312", "화학물 가공 장치 조작원"),
new JobCode("8319", "기타 석유 및 화학물 가공 장치 조작원"),
new JobCode("8321", "화학제품 생산기 조작원"),
new JobCode("8322", "타이어 및 고무제품 생산기 조작원"),
new JobCode("8323", "플라스틱제품 생산기 조작원"),
new JobCode("8324", "고무 및 플라스틱제품 조립원"),
new JobCode("8411", "주조기 조작원"),
new JobCode("8412", "단조기 조작원"),
new JobCode("8413", "용접기 조작원"),
new JobCode("8414", "금속가공 관련 제어 장치 조작원"),
new JobCode("8415", "금속가공 기계 조작원"),
new JobCode("8416", "제관기 조작원"),
new JobCode("8417", "판금기 조작원"),
new JobCode("8421", "도장기 조작원"),
new JobCode("8422", "도금 및 금속 분무기 조작원"),
new JobCode("8431", "유리 제조 및 가공기 조작원"),
new JobCode("8432", "점토제품 생산기 조작원"),
new JobCode("8433", "시멘트 및 광물제품 제조기 조작원"),
new JobCode("8434", "광석 및 석제품 가공기 조작원"),
new JobCode("8439", "기타 비금속제품 관련 생산기 조작원"),
new JobCode("8510", "금속 공작 기계 조작원"),
new JobCode("8520", "냉난방 관련 설비 조작원"),
new JobCode("8530", "자동 조립라인 및 산업용로봇 조작원"),
new JobCode("8541", "자동차 조립원"),
new JobCode("8542", "자동차 부품 조립원"),
new JobCode("8543", "운송장비 조립원"),
new JobCode("8544", "일반기계 조립원"),
new JobCode("8550", "금속기계 부품 조립원"),
new JobCode("8610", "발전 및 배전장치 조작원"),
new JobCode("8620", "전기 및 전자설비 조작원"),
new JobCode("8631", "전기 부품 및 제품 제조 기계 조작원"),
new JobCode("8632", "전자 부품 및 제품 제조 기계 조작원"),
new JobCode("8640", "전기∙전자 부품 및 제품 조립원"),
new JobCode("8710", "철도 및 전동차 기관사"),
new JobCode("8720", "철도운송 관련 종사원"),
new JobCode("8731", "택시 운전원"),
new JobCode("8732", "버스 운전원"),
new JobCode("8733", "화물차 및 특수차 운전원"),
new JobCode("8739", "기타 자동차 운전원"),
new JobCode("8740", "물품 이동 장비 조작원"),
new JobCode("8750", "건설 및 채굴기계 운전원"),
new JobCode("8760", "선박 승무원 및 관련 종사원"),
new JobCode("8810", "상하수도 처리 장치 조작원"),
new JobCode("8820", "재활용 처리 및 소각로 조작원"),
new JobCode("8911", "목재가공 관련 기계 조작원"),
new JobCode("8912", "가구 조립원"),
new JobCode("8913", "펄프 및 종이 제조 장치 조작원"),
new JobCode("8914", "종이제품 생산기 조작원"),
new JobCode("8919", "기타 목재 및 종이 관련 기계 조작원"),
new JobCode("8921", "인쇄기 조작원"),
new JobCode("8922", "사진 인화 및 현상기 조작원"),
new JobCode("8990", "기타 기계 조작원"),
new JobCode("9100", "건설 및 광업 단순 종사원"),
new JobCode("9210", "하역 및 적재 단순 종사원"),
new JobCode("9221", "우편집배원"),
new JobCode("9222", "택배원"),
new JobCode("9223", "음식 배달원"),
new JobCode("9229", "기타 배달원"),
new JobCode("9300", "제조 관련 단순 종사원"),
new JobCode("9411", "청소원"),
new JobCode("9412", "환경미화원 및 재활용품 수거원"),
new JobCode("9421", "건물 관리원"),
new JobCode("9422", "검표원"),
new JobCode("9511", "가사 도우미"),
new JobCode("9512", "육아 도우미"),
new JobCode("9521", "패스트푸드 준비원"),
new JobCode("9522", "주방 보조원"),
new JobCode("9531", "주유원"),
new JobCode("9539", "기타 판매 관련 단순 종사원"),
new JobCode("9910", "농림∙어업 관련 단순 종사원"),
new JobCode("9921", "계기 검침원 및 가스 점검원"),
new JobCode("9922", "자동판매기 관리원"),
new JobCode("9923", "주차 관리원 및 안내원"),
new JobCode("9991", "구두 미화원"),
new JobCode("9992", "세탁원 및 다림질원"),
new JobCode("9999", "기타 서비스 관련 단순 종사원"),
new JobCode("A011", "영관급 이상 장교"),
new JobCode("A012", "위관급 장교"),
new JobCode("A020", "부사관"),
new JobCode("A090", "기타 군인"),
new JobCode("a111", "어린이집원생"),
new JobCode("a112", "유치원생"),
new JobCode("a113", "초등학생"),
new JobCode("a114", "중학생"),
new JobCode("a115", "고등학생"),
new JobCode("a116", "대학생 이상"),
new JobCode("b111", "주부"),
new JobCode("c111", "무직")
                };
                }
                return _jobCodes;
            }
        }

        public LookupTest()
        {
            InitializeComponent();
            InitLookup();
        }

        private void InitLookup()
        {
            
            GridView isoView = gridLookUpEdit1.Properties.View as GridView;
            isoView.OptionsView.ShowAutoFilterRow = true;

            GridView jobView = lookupJob.Properties.View as GridView;
            jobView.OptionsView.ShowAutoFilterRow = true;
        }

        private void TreeListLookupTest_Load(object sender, EventArgs e)
        {
            //gridLookUpEdit1.DataBindings.Add(new Binding("Name", CreateDatas(), "Code"));

            gridLookUpEdit1.Properties.DataSource = this.GetIsoCodes;
            gridLookUpEdit1.Properties.DisplayMember = "Name";
            gridLookUpEdit1.Properties.ValueMember = "Code";

            lookupJob.Properties.DataSource = this.GetJobCodes;
            lookupJob.Properties.DisplayMember = "Name";
            lookupJob.Properties.ValueMember = "Code";
            //if (ptntNtnCds.Count > 0)
            //{
            //    gridLookUpEdit1.Properties.View.FocusedRowHandle = 0;
            //}
        }

        private void LookupTest_Shown(object sender, EventArgs e)
        {
            gridLookUpEdit1.EditValue = "KR";
            lookupJob.EditValue = "c111";
        }

        private void button1_Click(object sender, EventArgs e)
        {
            //gridLookUpEdit1.Properties.View.FocusedRowHandle = 0;

            gridLookUpEdit1.EditValue = "US";
        }

        private void gridLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            IsoCode isoCode = gridLookUpEdit1.GetSelectedDataRow() as IsoCode;

            if (isoCode != null)
            {
                txtIsoCode.Text = isoCode.Code;
                txtIsoName.Text = isoCode.Name;
            } else
            {
                txtIsoCode.Text = string.Empty;
                txtIsoName.Text = string.Empty;
            }
        }

        private void lookupJob_EditValueChanged(object sender, EventArgs e)
        {
            JobCode item = lookupJob.GetSelectedDataRow() as JobCode;

            if (item != null)
            {
                txtJobCode.Text = item.Code;
                txtJobName.Text = item.Name;
            } else
            {
                txtJobCode.Text = string.Empty;
                txtJobName.Text = string.Empty;
            }
        }

        private void gridLookUpEdit1_KeyUp(object sender, KeyEventArgs e)
        {
            if(e.KeyCode == Keys.Delete)
            {
                gridLookUpEdit1.EditValue = null;
            }
        }

        private void lookupJob_KeyUp(object sender, KeyEventArgs e)
        {
            if(e.KeyCode == Keys.Delete)
            {
                lookupJob.EditValue = null;
            }
        }
    }


    public class IsoCode
    {
        public IsoCode(string code, string name, string engName)
        {
            Code = code;
            Name = name;
            EngName = engName;

        }
        public string Code { get; set; }
        public string Name { get; set; }
        public string EngName { get; set; }
    }

    public class JobCode
    {
        public JobCode(string code, string name)
        {
            Code = code;
            Name = name;
        }

        public string Code { get; set; }
        public string Name { get; set; }
    }
}
